---

########################################################################################
- name: Configure all hosts (devops public keys)
  hosts: ubuntu
  become: yes
  become_user: vagrant

  tasks:
  - name: Install packages for ansible 2.4
   apt:
     name:
#       - unzip
#       - epel-release
#       - python-setuptools
       - python3
#       - python3-pip
#       - python-jinja2
#       - PyYAML.x86_64
#
