name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"
