name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run vagrant up
      run: vagrant up

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"
      
    - name: ssh ls
      run: vagrant ssh -c "ls -ltra"
    
    - name: ssh whoami
      run: vagrant ssh -c "whoami"
      
    - name: ssh lsb-release
      run: vagrant ssh -c "lsb-release -a"
